### ISSUE TITLE
Version 0.2.0. compatibility issue

### ISSUE THREAD

**Issue by hnikolas** [ClosedXML/ClosedXML.Extensions.Mvc#1]
Version 0.2.0 of ClosedXML.Extensions.Mvc seems to be incompatible with ClosedXML v0.93.0.
Below is the error message received.

"The type 'XLWorkbook' is defined in an assembly that is not referenced. You must add a reference to assembly 'ClosedXML, Version=0.92.1.0, Culture=neutral, PublicKeyToken=fd1eb21b62ae805b'"

**Comment by igitur** [comment]
Try https://www.nuget.org/packages/ClosedXML.Extensions.Mvc/0.2.1

It's based on the unsigned version of ClosedXML now.

**Comment by igitur** [comment]
And let me know if it solves it.

**Comment by hnikolas** [comment]
Yes this has resolved the issue 
Many thanks
