### ISSUE TITLE
the README could be more helpful

### ISSUE THREAD

**Issue by macginitie** [ClosedXML/ClosedXML.Extensions.Mvc#2]
The usefulness/helpfulness of the README would be increased "100%" (imo) if a sample implementation (no matter how simplified) of the "GenerateClosedXMLWorkbook()" method was included.

**Comment by igitur** [comment]
Good idea. Please submit the pull request.

**Comment by ice19942335** [comment]
Please more details in Read.me

**Comment by igitur** [comment]
@ice19942335 Don't expect me to do everything. You want something changed...? Then put in the effort and submit a pull request.
