### ISSUE TITLE
GenerateClosedXMLWorkbook not defined

### ISSUE THREAD

**Issue by maochaokuo** [ClosedXML/ClosedXML.Extensions.Mvc#3]
after I run (in a new asp.net mvc project)
Install-Package ClosedXML.Extensions.Mvc

then try your sample, but.... GenerateClosedXMLWorkbook not defined !!!
public ActionResult Download()
{
    using (var wb = GenerateClosedXMLWorkbook())
    {
        .......................

**Comment by igitur** [comment]
It is up to you to define `GenerateClosedXMLWorkbook()`.

**Comment by maochaokuo** [comment]
I see! Great. Thanks. Please forgive my stupidness.
