### ISSUE TITLE
No assembly for .NET Framework 4.8 available

### ISSUE THREAD

**Issue by Dehalion** [ClosedXML/ClosedXML.Extensions.Mvc#4]
The newest version (0.3) is not available for .NET Framework projects anymore.
Is there a technical reason for this or just an error introduced when upgrading the targets?

**Comment by igitur** [comment]
To be honest, I don't know. It's probably a mistake. 

But this project is so simple, you might as well just copy the code in https://github.com/ClosedXML/ClosedXML.Extensions.Mvc/blob/master/src/ClosedXML.Extensions.Mvc/MvcExtensions.cs directly into your project and not depend on yet another NuGet package.

**Comment by igitur** [comment]
Ok, I recall what I did here. I just wanted to make the NuGet package as lightweight as possible and in v0.3 I dropped support for .NET Fx. v0.2 should work perfectly for you. I'll add some comments in the README.
